package pe.edu.unsch.entities;
// Generated 23/06/2019 06:32:43 PM by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bachiller generated by hbm2java
 */
@Entity
@Table(name = "bachiller", catalog = "tesisexperienciaprofesional", uniqueConstraints = @UniqueConstraint(columnNames = "dni"))
public class Bachiller implements java.io.Serializable {

	private String codigo;
	private String dni;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String escuela;
	private String email;
	private String telefono;
	private String nombreCompleto;
	@JsonIgnore
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

	public Bachiller() {
	}

	public Bachiller(String codigo, String dni, String nombre, String apellidoPaterno, String apellidoMaterno,
			String escuela, String email, String telefono, String nombreCompleto) {
		this.codigo = codigo;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.escuela = escuela;
		this.email = email;
		this.telefono = telefono;
		this.nombreCompleto = nombreCompleto;
	}

	public Bachiller(String codigo, String dni, String nombre, String apellidoPaterno, String apellidoMaterno,
			String escuela, String email, String telefono, String nombreCompleto, Set<Solicitud> solicituds) {
		this.codigo = codigo;
		this.dni = dni;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.escuela = escuela;
		this.email = email;
		this.telefono = telefono;
		this.nombreCompleto = nombreCompleto;
		this.solicituds = solicituds;
	}

	@Id

	@Column(name = "codigo", nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "dni", nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidoPaterno", nullable = false, length = 50)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellidoMaterno", nullable = false, length = 50)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "escuela", nullable = false, length = 45)
	public String getEscuela() {
		return this.escuela;
	}

	public void setEscuela(String escuela) {
		this.escuela = escuela;
	}

	@Column(name = "email", nullable = false, length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", nullable = false, length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "nombreCompleto", nullable = false, length = 500)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bachiller")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	/*@Override
	public String toString() {
		return "Bachiller [codigo=" + codigo + ", dni=" + dni + ", nombre=" + nombre + ", apellidoPaterno="
				+ apellidoPaterno + ", apellidoMaterno=" + apellidoMaterno + ", escuela=" + escuela + ", email=" + email
				+ ", telefono=" + telefono + ", nombreCompleto=" + nombreCompleto + ", solicituds=" + solicituds + "]";
	}*/
	
	

}
