// default package
// Generated 13/06/2019 02:30:17 PM by Hibernate Tools 5.1.10.Final

package pe.edu.unsch.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comisiondictaminadora generated by hbm2java
 */
@Entity
@Table(name = "comisiondictaminadora", catalog = "tesisexperienciaprofesional")
public class Comisiondictaminadora implements java.io.Serializable {

	private int idComisionDictaminadora;

	public Comisiondictaminadora() {
	}

	public Comisiondictaminadora(int idComisionDictaminadora) {
		this.idComisionDictaminadora = idComisionDictaminadora;
	}

	@Id

	@Column(name = "idComisionDictaminadora", unique = true, nullable = false)
	public int getIdComisionDictaminadora() {
		return this.idComisionDictaminadora;
	}

	public void setIdComisionDictaminadora(int idComisionDictaminadora) {
		this.idComisionDictaminadora = idComisionDictaminadora;
	}

}
