// default package
// Generated 13/06/2019 02:30:17 PM by Hibernate Tools 5.1.10.Final
package pe.edu.unsch.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Consejofacultad generated by hbm2java
 */
@Entity
@Table(name = "consejofacultad", catalog = "tesisexperienciaprofesional")
public class Consejofacultad implements java.io.Serializable {

	private int idConsejoFacultad;

	public Consejofacultad() {
	}

	public Consejofacultad(int idConsejoFacultad) {
		this.idConsejoFacultad = idConsejoFacultad;
	}

	@Id

	@Column(name = "idConsejoFacultad", unique = true, nullable = false)
	public int getIdConsejoFacultad() {
		return this.idConsejoFacultad;
	}

	public void setIdConsejoFacultad(int idConsejoFacultad) {
		this.idConsejoFacultad = idConsejoFacultad;
	}

}
