// default package
// Generated 13/06/2019 02:30:17 PM by Hibernate Tools 5.1.10.Final
package pe.edu.unsch.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Constanciadeaprobacion generated by hbm2java
 */
@Entity
@Table(name = "constanciadeaprobacion", catalog = "tesisexperienciaprofesional")
public class Constanciadeaprobacion implements java.io.Serializable {

	private int idConstanciaDeAprobacion;
	private int idDocumento;
	private String codigo;

	public Constanciadeaprobacion() {
	}

	public Constanciadeaprobacion(int idConstanciaDeAprobacion, int idDocumento, String codigo) {
		this.idConstanciaDeAprobacion = idConstanciaDeAprobacion;
		this.idDocumento = idDocumento;
		this.codigo = codigo;
	}

	@Id

	@Column(name = "idConstanciaDeAprobacion", unique = true, nullable = false)
	public int getIdConstanciaDeAprobacion() {
		return this.idConstanciaDeAprobacion;
	}

	public void setIdConstanciaDeAprobacion(int idConstanciaDeAprobacion) {
		this.idConstanciaDeAprobacion = idConstanciaDeAprobacion;
	}

	@Column(name = "idDocumento", nullable = false)
	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "codigo", nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
