package pe.edu.unsch.entities;
// Generated 13/06/2019 07:12:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dictamen generated by hbm2java
 */
@Entity
@Table(name = "dictamen", catalog = "tesisexperienciaprofesional")
public class Dictamen implements java.io.Serializable {

	private int idDictamen;
	private int idDocumento;
	private int idCominsionDictaminadora;

	public Dictamen() {
	}

	public Dictamen(int idDictamen, int idDocumento, int idCominsionDictaminadora) {
		this.idDictamen = idDictamen;
		this.idDocumento = idDocumento;
		this.idCominsionDictaminadora = idCominsionDictaminadora;
	}

	@Id

	@Column(name = "idDictamen", unique = true, nullable = false)
	public int getIdDictamen() {
		return this.idDictamen;
	}

	public void setIdDictamen(int idDictamen) {
		this.idDictamen = idDictamen;
	}

	@Column(name = "idDocumento", nullable = false)
	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "idCominsionDictaminadora", nullable = false)
	public int getIdCominsionDictaminadora() {
		return this.idCominsionDictaminadora;
	}

	public void setIdCominsionDictaminadora(int idCominsionDictaminadora) {
		this.idCominsionDictaminadora = idCominsionDictaminadora;
	}

}
