// default package
// Generated 13/06/2019 02:30:17 PM by Hibernate Tools 5.1.10.Final
package pe.edu.unsch.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notadesustentacion generated by hbm2java
 */
@Entity
@Table(name = "notadesustentacion", catalog = "tesisexperienciaprofesional")
public class Notadesustentacion implements java.io.Serializable {

	private int idNotaDeSustentacion;
	private int idJurado;
	private String codigo;
	private int calificacion;

	public Notadesustentacion() {
	}

	public Notadesustentacion(int idNotaDeSustentacion, int idJurado, String codigo, int calificacion) {
		this.idNotaDeSustentacion = idNotaDeSustentacion;
		this.idJurado = idJurado;
		this.codigo = codigo;
		this.calificacion = calificacion;
	}

	@Id

	@Column(name = "idNotaDeSustentacion", unique = true, nullable = false)
	public int getIdNotaDeSustentacion() {
		return this.idNotaDeSustentacion;
	}

	public void setIdNotaDeSustentacion(int idNotaDeSustentacion) {
		this.idNotaDeSustentacion = idNotaDeSustentacion;
	}

	@Column(name = "idJurado", nullable = false)
	public int getIdJurado() {
		return this.idJurado;
	}

	public void setIdJurado(int idJurado) {
		this.idJurado = idJurado;
	}

	@Column(name = "codigo", nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Calificacion", nullable = false)
	public int getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(int calificacion) {
		this.calificacion = calificacion;
	}

}
