// default package
// Generated 13/06/2019 02:30:17 PM by Hibernate Tools 5.1.10.Final
package pe.edu.unsch.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Presidentecomisionacademina generated by hbm2java
 */
@Entity
@Table(name = "presidentecomisionacademina", catalog = "tesisexperienciaprofesional")
public class Presidentecomisionacademina implements java.io.Serializable {

	private int idPresidenteComisionAcademina;

	public Presidentecomisionacademina() {
	}

	public Presidentecomisionacademina(int idPresidenteComisionAcademina) {
		this.idPresidenteComisionAcademina = idPresidenteComisionAcademina;
	}

	@Id

	@Column(name = "idPresidenteComisionAcademina", unique = true, nullable = false)
	public int getIdPresidenteComisionAcademina() {
		return this.idPresidenteComisionAcademina;
	}

	public void setIdPresidenteComisionAcademina(int idPresidenteComisionAcademina) {
		this.idPresidenteComisionAcademina = idPresidenteComisionAcademina;
	}

}
