package pe.edu.unsch.entities;
// Generated 13/06/2019 07:12:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resoluciondecanal generated by hbm2java
 */
@Entity
@Table(name = "resoluciondecanal", catalog = "tesisexperienciaprofesional")
public class Resoluciondecanal implements java.io.Serializable {

	private int idResolucionDecanal;
	private int idDocumento;

	public Resoluciondecanal() {
	}

	public Resoluciondecanal(int idResolucionDecanal, int idDocumento) {
		this.idResolucionDecanal = idResolucionDecanal;
		this.idDocumento = idDocumento;
	}

	@Id

	@Column(name = "idResolucionDecanal", unique = true, nullable = false)
	public int getIdResolucionDecanal() {
		return this.idResolucionDecanal;
	}

	public void setIdResolucionDecanal(int idResolucionDecanal) {
		this.idResolucionDecanal = idResolucionDecanal;
	}

	@Column(name = "idDocumento", nullable = false)
	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

}
