package pe.edu.unsch.entities;
// Generated 13/06/2019 07:12:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", catalog = "tesisexperienciaprofesional", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Solicitud implements java.io.Serializable {

	private int idSolicitud;
	private int idDocumento;
	private String codigo;
	private String dni;

	public Solicitud() {
	}

	public Solicitud(int idSolicitud, int idDocumento, String codigo, String dni) {
		this.idSolicitud = idSolicitud;
		this.idDocumento = idDocumento;
		this.codigo = codigo;
		this.dni = dni;
	}

	@Id

	@Column(name = "idSolicitud", unique = true, nullable = false)
	public int getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@Column(name = "idDocumento", nullable = false)
	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "dni", nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

}
