package pe.edu.unsch.entities;
// Generated 23/06/2019 06:32:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.*;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", catalog = "tesisexperienciaprofesional", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Solicitud implements java.io.Serializable {

	private int idSolicitud;
	private Bachiller bachiller;
	private Decano decano;
	private Documento documento;

	public Solicitud() {
	}

	public Solicitud(int idSolicitud, Bachiller bachiller, Decano decano, Documento documento) {
		this.idSolicitud = idSolicitud;
		this.bachiller = bachiller;
		this.decano = decano;
		this.documento = documento;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idSolicitud", unique = true, nullable = false)
	public int getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo", unique = true, nullable = false)
	public Bachiller getBachiller() {
		return this.bachiller;
	}

	public void setBachiller(Bachiller bachiller) {
		this.bachiller = bachiller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni", nullable = false)
	public Decano getDecano() {
		return this.decano;
	}

	public void setDecano(Decano decano) {
		this.decano = decano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocumento", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	/*@Override
	public String toString() {
		return "Solicitud [idSolicitud=" + idSolicitud + ", bachiller=" + bachiller + ", decano=" + decano
				+ ", documento=" + documento + "]";
	}*/
	
	

}
