package pe.edu.unsch.entities;
// Generated 13/06/2019 07:12:27 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tituloprofesional generated by hbm2java
 */
@Entity
@Table(name = "tituloprofesional", catalog = "tesisexperienciaprofesional")
public class Tituloprofesional implements java.io.Serializable {

	private int idTituloProfesional;
	private String codigo;
	private int idResolucionDecanal;

	public Tituloprofesional() {
	}

	public Tituloprofesional(int idTituloProfesional, String codigo, int idResolucionDecanal) {
		this.idTituloProfesional = idTituloProfesional;
		this.codigo = codigo;
		this.idResolucionDecanal = idResolucionDecanal;
	}

	@Id

	@Column(name = "idTituloProfesional", unique = true, nullable = false)
	public int getIdTituloProfesional() {
		return this.idTituloProfesional;
	}

	public void setIdTituloProfesional(int idTituloProfesional) {
		this.idTituloProfesional = idTituloProfesional;
	}

	@Column(name = "codigo", nullable = false, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "idResolucionDecanal", nullable = false)
	public int getIdResolucionDecanal() {
		return this.idResolucionDecanal;
	}

	public void setIdResolucionDecanal(int idResolucionDecanal) {
		this.idResolucionDecanal = idResolucionDecanal;
	}

}
