-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 22:59:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tesisExperienciaProfesional
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tesisExperienciaProfesional` ;

-- -----------------------------------------------------
-- Schema tesisExperienciaProfesional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tesisExperienciaProfesional` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `tesisExperienciaProfesional` ;

-- -----------------------------------------------------
-- Table `ActaDesSustentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ActaDesSustentacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ActaDesSustentacion` (
  `idActaDeSustentacion` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  `idJuradoCalificador` INT NOT NULL,
  `idNotaDeSustentacion` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idActaDeSustentacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Bachiller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bachiller` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Bachiller` (
  `codigo` VARCHAR(8) NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `escuela` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_UNIQUE` ON `Bachiller` (`codigo` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `Bachiller` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ComisionDictaminadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ComisionDictaminadora` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ComisionDictaminadora` (
  `idComisionDictaminadora` INT NOT NULL,
  PRIMARY KEY (`idComisionDictaminadora`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idComisionDictaminadora_UNIQUE` ON `ComisionDictaminadora` (`idComisionDictaminadora` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ConsejoFacultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConsejoFacultad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ConsejoFacultad` (
  `idConsejoFacultad` INT NOT NULL,
  PRIMARY KEY (`idConsejoFacultad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ConstanciaDeAprobacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ConstanciaDeAprobacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ConstanciaDeAprobacion` (
  `idConstanciaDeAprobacion` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idConstanciaDeAprobacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Decano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Decano` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Decano` (
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `Decano` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Dictamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dictamen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Dictamen` (
  `idDictamen` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  `idCominsionDictaminadora` INT NOT NULL,
  PRIMARY KEY (`idDictamen`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDictamen_UNIQUE` ON `Dictamen` (`idDictamen` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DirectorEscuela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DirectorEscuela` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DirectorEscuela` (
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `DirectorEscuela` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Documento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Documento` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `tipoDocumento` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idDocumento`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idResolucionDecanalI_UNIQUE` ON `Documento` (`idDocumento` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `JuradoCalificador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JuradoCalificador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `JuradoCalificador` (
  `idJuradoCalificador` INT NOT NULL,
  PRIMARY KEY (`idJuradoCalificador`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idJuradoCalificador_UNIQUE` ON `JuradoCalificador` (`idJuradoCalificador` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MemorandoMultiple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MemorandoMultiple` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MemorandoMultiple` (
  `idMemorandoMultiple` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  PRIMARY KEY (`idMemorandoMultiple`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `NotaDeSustentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NotaDeSustentacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `NotaDeSustentacion` (
  `idNotaDeSustentacion` INT NOT NULL,
  `idJurado` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `Calificacion` INT(2) NOT NULL,
  PRIMARY KEY (`idNotaDeSustentacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PresidenteComisionAcademina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PresidenteComisionAcademina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PresidenteComisionAcademina` (
  `idPresidenteComisionAcademina` INT NOT NULL,
  PRIMARY KEY (`idPresidenteComisionAcademina`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPresidenteComisionAcademina_UNIQUE` ON `PresidenteComisionAcademina` (`idPresidenteComisionAcademina` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ResolucionDecanal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResolucionDecanal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ResolucionDecanal` (
  `idResolucionDecanal` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  PRIMARY KEY (`idResolucionDecanal`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idResolucionDecanal_UNIQUE` ON `ResolucionDecanal` (`idResolucionDecanal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SecreatrioFacultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SecreatrioFacultad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SecreatrioFacultad` (
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `SecreatrioFacultad` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Solicitud` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Solicitud` (
  `idSolicitud` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idSolicitud`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idtable1_UNIQUE` ON `Solicitud` (`idSolicitud` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `codigo_UNIQUE` ON `Solicitud` (`codigo` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TituloProfesional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TituloProfesional` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TituloProfesional` (
  `idTituloProfesional` INT NOT NULL,
  `codigo` VARCHAR(8) NOT NULL,
  `idResolucionDecanal` INT NOT NULL,
  PRIMARY KEY (`idTituloProfesional`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
